### ISSUE TITLE
enviroment variables needed to run

### ISSUE THREAD

**Issue by nicolasassi** [ncruces/go-gcf#1]
Currently you need to set some env. vars with specific keys so you can use the API. I think this is the kind of thing that should be documented as I could only figure out by looking at the source code

**Comment by ncruces** [comment]
Are [these](https://github.com/ncruces/go-gcf/blob/acd6fa2351fc13f8f18c1dec13e3cf7c02642a61/logging/logging.go#L35) what you mean?

They were supposed to be set by the environment [automatically](https://cloud.google.com/functions/docs/env-var#environment_variables_set_automatically), and where on the Go 1.11 runtime. This seems to have changed for the more recent Go 1.13 runtime.

I still haven't updated my functions (and this package) to Go 1.13.

Is this the only change required?

**Comment by nicolasassi** [comment]
Thanks for the quick reply!

Just read the docs for gcloud functions and Go 1.13 and it seems that the env vars needed for your project to work are not supported... Not sure they will change that in the future.

Anyway, currently I'm setting the required env vars and works fine.

**Comment by ncruces** [comment]
If setting the environment variables is all that is needed, and there is no better way to do it, I'll definitely add that to the docs.

Reopening to remind me to do it.

Thanks for the report!

**Comment by ncruces** [comment]
Hi @nicolasassi, I found a way to do this, that's compatible with Cloud Run and requires zero configuration.

Please consider upgrading to: [github.com/ncruces/go-gcp/glog](https://pkg.go.dev/github.com/ncruces/go-gcp/glog)
